name: snap_toast_flutter_example
description: Demo app for the snap_toast_flutter package.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  snap_toast_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
